"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { useSelectedLayoutSegments } from "next/navigation";
import BottomNavbar from "./components/navbar/BottomNavbar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const segments = useSelectedLayoutSegments();
  const [modalOpen, setModalOpen] = useState(false);

  return (
    <html lang="en" className="bg-slate-300">
      <body className={inter.className}>
        <div className="h-[90vh] p-2">{children}</div>

        {/* Bottom Navigation */}
        <div className="h-[10vh] flex justify-center items-center pb-2">
          <BottomNavbar segments={segments} setModalOpen={setModalOpen} />
        </div>
      </body>
    </html>
  );
}
